### ISSUE TITLE
Cannot generate Blueprint

### ISSUE THREAD

**Issue by shideneyu** [connexio-labs/grape-apiary#3]
Using `rails_console`

    irb(main):008:0> GrapeApiary::Blueprint(Api::V1::Pages).generate
    NoMethodError: undefined method `Blueprint' for GrapeApiary:Module
      from (irb):8
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/commands/console.rb:110:in `start'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/commands/console.rb:9:in `start'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:68:in `console'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
      from /home/shideneyu/projects/Textmaster/webscrap_master_service/bin/rails:4:in `<top (required)>'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/commands/rails.rb:6:in `call'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/command_wrapper.rb:38:in `call'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/application.rb:183:in `block in serve'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/application.rb:156:in `fork'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/application.rb:156:in `serve'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/application.rb:131:in `block in run'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/application.rb:125:in `loop'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/application.rb:125:in `run'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/application/boot.rb:18:in `<top (required)>'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'

**Comment by shideneyu** [comment]
Poor my, it was a typo issue.

    GrapeApiary::Blueprint.new(Api::V1::Pages).generate
